name: ROS2 Humble CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python_lint:
    name: Python Lint
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    strategy:
      matrix:
        linter: [copyright, flake8, mypy, pep257, pep8, xmllint]
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: humble
          import-token: ${{ secrets.GITHUB_TOKEN }}
          store-log-artifacts: true
